import { ColumnSchema, TableSchemaInfo } from './types.js';

/**
 * Converts snake_case or table name to PascalCase singular (e.g. "users" -> "User")
 */
export function toPascalCase(str: string): string {
   // Remove trailing 's' if simple plural (e.g. 'users' -> 'user', 'orders' -> 'order')
   let s = str;
   if (
      s.length > 3 &&
      s.endsWith('s') &&
      !s.endsWith('ss') &&
      !s.endsWith('us')
   ) {
      s = s.slice(0, -1);
   }
   return s
      .replace(/[^a-zA-Z0-9_]/g, '_')
      .split('_')
      .filter(Boolean)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('');
}

/**
 * Converts identifier to valid camelCase
 */
export function toCamelCase(str: string): string {
   const parts = str
      .replace(/[^a-zA-Z0-9_]/g, '_')
      .split('_')
      .filter(Boolean);
   if (parts.length === 0) return str;
   return (
      parts[0].toLowerCase() +
      parts
         .slice(1)
         .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
         .join('')
   );
}

/**
 * Generates Prisma Schema file (.prisma)
 */
export function generatePrismaSchema(
   tables: TableSchemaInfo[],
   dbType: string = 'postgres',
): string {
   let provider = 'postgresql';
   if (dbType === 'sqlite') provider = 'sqlite';
   else if (dbType === 'mysql') provider = 'mysql';

   let out = `// ==========================================\n`;
   out += `// Prisma Schema generated by Drixio\n`;
   out += `// Dialect: ${provider}\n`;
   out += `// ==========================================\n\n`;
   out += `datasource db {\n`;
   out += `  provider = "${provider}"\n`;
   out += `  url      = env("DATABASE_URL")\n`;
   out += `}\n\n`;
   out += `generator client {\n`;
   out += `  provider = "prisma-client-js"\n`;
   out += `}\n\n`;

   if (tables.length === 0) {
      out += `// No tables found in database.\n`;
      return out;
   }

   for (const table of tables) {
      const modelName = toPascalCase(table.tableName) || 'Model';
      out += `model ${modelName} {\n`;

      const fieldLines: { name: string; type: string; attributes: string }[] =
         [];

      for (const col of table.columns) {
         const fieldName = toCamelCase(col.name) || col.name;
         const lowerType = (col.type || 'text').toLowerCase();

         let prismaType = 'String';
         let isAutoInc = false;

         if (
            lowerType.includes('int') ||
            lowerType.includes('serial') ||
            lowerType === 'year'
         ) {
            if (lowerType.includes('bigint')) {
               prismaType = 'BigInt';
            } else {
               prismaType = 'Int';
            }
            if (col.isPk || lowerType.includes('serial')) {
               isAutoInc = true;
            }
         } else if (
            lowerType.includes('float') ||
            lowerType.includes('double') ||
            lowerType.includes('real')
         ) {
            prismaType = 'Float';
         } else if (
            lowerType.includes('decimal') ||
            lowerType.includes('numeric')
         ) {
            prismaType = 'Decimal';
         } else if (lowerType.includes('bool') || lowerType === 'tinyint(1)') {
            prismaType = 'Boolean';
         } else if (lowerType.includes('date') || lowerType.includes('time')) {
            prismaType = 'DateTime';
         } else if (lowerType.includes('json')) {
            prismaType = 'Json';
         } else if (
            lowerType.includes('blob') ||
            lowerType.includes('bytea') ||
            lowerType.includes('binary')
         ) {
            prismaType = 'Bytes';
         }

         // Optionality
         const isNullable = col.nullable && !col.isPk;
         const typeSuffix = isNullable ? '?' : '';

         // Attributes
         const attrs: string[] = [];
         if (col.isPk) {
            attrs.push('@id');
            if (isAutoInc && provider !== 'sqlite') {
               attrs.push('@default(autoincrement())');
            } else if (
               isAutoInc &&
               provider === 'sqlite' &&
               prismaType === 'Int'
            ) {
               attrs.push('@default(autoincrement())');
            }
         }

         if (col.isUnique && !col.isPk) {
            attrs.push('@unique');
         }

         if (col.defaultValue !== undefined && col.defaultValue !== null) {
            const rawDef = col.defaultValue.trim();
            if (
               rawDef.toUpperCase().includes('CURRENT_TIMESTAMP') ||
               rawDef.toUpperCase().includes('NOW()')
            ) {
               attrs.push('@default(now())');
            } else if (
               rawDef.toLowerCase() === 'true' ||
               rawDef.toLowerCase() === 'false'
            ) {
               attrs.push(`@default(${rawDef.toLowerCase()})`);
            } else if (!isNaN(Number(rawDef)) && rawDef !== '') {
               attrs.push(`@default(${rawDef})`);
            } else if (rawDef.toUpperCase().includes('UUID')) {
               attrs.push('@default(uuid())');
            } else if (rawDef !== '') {
               const cleanStr = rawDef.replace(/^['"]|['"]$/g, '');
               attrs.push(`@default("${cleanStr}")`);
            }
         }

         if (fieldName !== col.name) {
            attrs.push(`@map("${col.name}")`);
         }

         fieldLines.push({
            name: fieldName,
            type: `${prismaType}${typeSuffix}`,
            attributes: attrs.join(' '),
         });
      }

      // Format aligned columns
      const maxNameLen = Math.max(...fieldLines.map((f) => f.name.length), 0);
      const maxTypeLen = Math.max(...fieldLines.map((f) => f.type.length), 0);

      for (const f of fieldLines) {
         const paddedName = f.name.padEnd(maxNameLen, ' ');
         const paddedType = f.type.padEnd(maxTypeLen, ' ');
         const attrStr = f.attributes ? ` ${f.attributes}` : '';
         out += `  ${paddedName}  ${paddedType}${attrStr}\n`;
      }

      if (modelName.toLowerCase() !== table.tableName.toLowerCase()) {
         out += `\n  @@map("${table.tableName}")\n`;
      }

      out += `}\n\n`;
   }

   return out.trim() + '\n';
}

/**
 * Generates Drizzle ORM schema (.ts)
 */
export function generateDrizzleSchema(
   tables: TableSchemaInfo[],
   dbType: string = 'postgres',
): string {
   const dialect =
      dbType === 'sqlite'
         ? 'sqlite'
         : dbType === 'mysql'
           ? 'mysql'
           : 'postgres';

   let out = `// ==========================================\n`;
   out += `// Drizzle ORM Schema generated by Drixio\n`;
   out += `// Dialect: ${dialect}\n`;
   out += `// ==========================================\n\n`;

   if (dialect === 'sqlite') {
      out += `import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';\n`;
      out += `import { sql } from 'drizzle-orm';\n\n`;
   } else if (dialect === 'mysql') {
      out += `import { mysqlTable, varchar, text, int, serial, boolean, datetime, json } from 'drizzle-orm/mysql-core';\n`;
      out += `import { sql } from 'drizzle-orm';\n\n`;
   } else {
      out += `import { pgTable, varchar, text, integer, serial, boolean, timestamp, jsonb, doublePrecision } from 'drizzle-orm/pg-core';\n`;
      out += `import { sql } from 'drizzle-orm';\n\n`;
   }

   if (tables.length === 0) {
      out += `// No tables found in database.\n`;
      return out;
   }

   for (const table of tables) {
      const varName = toCamelCase(table.tableName) || 'tableItem';
      const tblFn =
         dialect === 'sqlite'
            ? 'sqliteTable'
            : dialect === 'mysql'
              ? 'mysqlTable'
              : 'pgTable';

      out += `export const ${varName} = ${tblFn}('${table.tableName}', {\n`;

      for (const col of table.columns) {
         const colProp = toCamelCase(col.name) || col.name;
         const lowerType = (col.type || 'text').toLowerCase();

         let defChain = '';

         if (dialect === 'sqlite') {
            if (lowerType.includes('int')) {
               if (col.isPk) {
                  defChain = `integer('${col.name}').primaryKey({ autoIncrement: true })`;
               } else {
                  defChain = `integer('${col.name}')`;
               }
            } else if (
               lowerType.includes('real') ||
               lowerType.includes('float') ||
               lowerType.includes('double') ||
               lowerType.includes('num')
            ) {
               defChain = `real('${col.name}')`;
               if (col.isPk) defChain += `.primaryKey()`;
            } else {
               defChain = `text('${col.name}')`;
               if (col.isPk) defChain += `.primaryKey()`;
            }
         } else if (dialect === 'mysql') {
            if (
               col.isPk &&
               (lowerType.includes('int') || lowerType.includes('serial'))
            ) {
               defChain = `serial('${col.name}').primaryKey()`;
            } else if (lowerType.includes('int')) {
               defChain = `int('${col.name}')`;
               if (col.isPk) defChain += `.primaryKey()`;
            } else if (
               lowerType.includes('bool') ||
               lowerType === 'tinyint(1)'
            ) {
               defChain = `boolean('${col.name}')`;
            } else if (
               lowerType.includes('date') ||
               lowerType.includes('time')
            ) {
               defChain = `datetime('${col.name}')`;
            } else if (lowerType.includes('json')) {
               defChain = `json('${col.name}')`;
            } else if (lowerType.includes('varchar')) {
               const lenMatch = lowerType.match(/\((\d+)\)/);
               const len = lenMatch ? lenMatch[1] : '255';
               defChain = `varchar('${col.name}', { length: ${len} })`;
               if (col.isPk) defChain += `.primaryKey()`;
            } else {
               defChain = `text('${col.name}')`;
               if (col.isPk) defChain += `.primaryKey()`;
            }
         } else {
            // Postgres
            if (
               col.isPk &&
               (lowerType.includes('serial') || lowerType.includes('int'))
            ) {
               defChain = `serial('${col.name}').primaryKey()`;
            } else if (lowerType.includes('int')) {
               defChain = `integer('${col.name}')`;
               if (col.isPk) defChain += `.primaryKey()`;
            } else if (lowerType.includes('bool')) {
               defChain = `boolean('${col.name}')`;
            } else if (
               lowerType.includes('float') ||
               lowerType.includes('double') ||
               lowerType.includes('real')
            ) {
               defChain = `doublePrecision('${col.name}')`;
            } else if (
               lowerType.includes('date') ||
               lowerType.includes('time')
            ) {
               defChain = `timestamp('${col.name}', { mode: 'string' })`;
            } else if (lowerType.includes('json')) {
               defChain = `jsonb('${col.name}')`;
            } else if (lowerType.includes('varchar')) {
               const lenMatch = lowerType.match(/\((\d+)\)/);
               const len = lenMatch ? lenMatch[1] : '255';
               defChain = `varchar('${col.name}', { length: ${len} })`;
               if (col.isPk) defChain += `.primaryKey()`;
            } else {
               defChain = `text('${col.name}')`;
               if (col.isPk) defChain += `.primaryKey()`;
            }
         }

         // Modifiers
         if (!col.nullable && !defChain.includes('.primaryKey()')) {
            defChain += `.notNull()`;
         }

         if (col.isUnique && !defChain.includes('.primaryKey()')) {
            defChain += `.unique()`;
         }

         if (col.defaultValue !== undefined && col.defaultValue !== null) {
            const rawDef = col.defaultValue.trim();
            if (
               rawDef.toUpperCase().includes('CURRENT_TIMESTAMP') ||
               rawDef.toUpperCase().includes('NOW()')
            ) {
               if (dialect === 'postgres') {
                  defChain += `.defaultNow()`;
               } else {
                  defChain += `.default(sql\`CURRENT_TIMESTAMP\`)`;
               }
            } else if (
               rawDef.toLowerCase() === 'true' ||
               rawDef.toLowerCase() === 'false'
            ) {
               defChain += `.default(${rawDef.toLowerCase()})`;
            } else if (!isNaN(Number(rawDef)) && rawDef !== '') {
               defChain += `.default(${rawDef})`;
            } else if (rawDef !== '') {
               const cleanStr = rawDef.replace(/^['"]|['"]$/g, '');
               defChain += `.default('${cleanStr}')`;
            }
         }

         out += `  ${colProp}: ${defChain},\n`;
      }

      out += `});\n\n`;
   }

   return out.trim() + '\n';
}

/**
 * Map generic SQL column type to TypeScript primitive type
 */
export function mapSqlTypeToTs(sqlType: string): string {
   const type = (sqlType || '').toLowerCase();
   if (
      type.includes('int') ||
      type.includes('num') ||
      type.includes('float') ||
      type.includes('double') ||
      type.includes('real')
   ) {
      return 'number';
   }
   if (type.includes('bool') || type === 'tinyint(1)') {
      return 'boolean';
   }
   if (
      type.includes('char') ||
      type.includes('text') ||
      type.includes('uuid') ||
      type.includes('string')
   ) {
      return 'string';
   }
   if (type.includes('date') || type.includes('time')) {
      return 'Date';
   }
   if (type.includes('json')) {
      return 'any';
   }
   return 'string';
}

/**
 * Generate TypeScript interface definitions for tables.
 */
export function generateTypeScriptDefinitions(
   tables: TableSchemaInfo[],
   dbType: string = 'database',
): string {
   let tsCode = `// Generated by Drixio\n// Database: ${dbType.toUpperCase()}\n\n`;

   for (const table of tables) {
      const interfaceName = toPascalCase(table.tableName);
      tsCode += `export interface ${interfaceName} {\n`;

      for (const col of table.columns) {
         const tsType = mapSqlTypeToTs(col.type);
         const optionalFlag = col.nullable ? '?' : '';
         tsCode += `  ${col.name}${optionalFlag}: ${tsType};\n`;
      }
      tsCode += `}\n\n`;
   }

   return tsCode.trim() + '\n';
}

